#!/usr/bin/env python3
"""
generate_data.py — Converts JSON data files to JS modules for TeluguLingo
and auto-updates the src/data/index.js file.

Usage:
    python generate_data.py                  # run from d:/dev/Lingo
    python generate_data.py --dry-run        # preview what would be written

What it does:
  - Walks every *.json file under  <root>/json-data/
  - Mirrors the folder hierarchy into <root>/src/data/
  - Writes (or updates) a .js file that re-exports the JSON
  - Updates src/data/index.js if new files are discovered

Example:
  json-data/Section_1/01_Overview_Telugu.json
    → src/data/Section_1/01_Overview_Telugu.js
    → Adds to index.js
"""

import argparse
import os
import re
import sys
from pathlib import Path

# ── Paths ──────────────────────────────────────────────────────────────────────
SCRIPT_DIR  = Path(__file__).parent.resolve()
JSON_ROOT   = SCRIPT_DIR / "json-data"
JS_ROOT     = SCRIPT_DIR / "src" / "data"

# ── Template ───────────────────────────────────────────────────────────────────
TEMPLATE = """\
// Auto-generated by generate_data.py — do not edit manually.
// Source: {source_rel}
import data from "{import_path}";

export default data;
"""


def json_to_js_path(json_path: Path) -> Path:
    """Return the target .js path for a given source .json path."""
    rel = json_path.relative_to(JSON_ROOT)
    return JS_ROOT / rel.with_suffix(".js")


def compute_import_path(js_path: Path, json_path: Path) -> str:
    """Return the relative POSIX import path from js_path → json_path."""
    rel = os.path.relpath(json_path, js_path.parent)
    return Path(rel).as_posix()


def update_index_js(js_path: Path, dry_run: bool):
    """Update index.js with the new imported section if it does not exist."""
    file_name = js_path.stem
    section_name = js_path.parent.name
    index_path = JS_ROOT / "index.js"
    
    if not index_path.exists():
        return False
        
    content = index_path.read_text(encoding="utf-8")
    import_path = f"./{section_name}/{file_name}"
    
    if f'from "{import_path}"' in content or f"from '{import_path}'" in content or f'from "{import_path}.js"' in content:
        return False # already there
        
    if dry_run:
        return True
        
    # Generate unique variable name (e.g., section1BasicTeluguPronouns)
    var_name = "".join(word.capitalize() for word in re.split(r'[^a-zA-Z0-9]', file_name) if word)
    var_name = section_name.replace('_', '').lower() + var_name
    
    import_stmt = f'import {var_name} from "{import_path}";'
    
    # 1. Insert import statement
    import_match = list(re.finditer(r'^import .*?;$', content, re.MULTILINE))
    if import_match:
        pos = import_match[-1].end()
        content = content[:pos] + '\n' + import_stmt + content[pos:]
    else:
        # Before export const SECTIONS if no imports
        pos = content.find('export const SECTIONS')
        if pos != -1:
            content = content[:pos] + import_stmt + '\n\n' + content[pos:]
        
    # 2. Insert category object
    section_id = section_name.lower()
    section_label = section_name.replace('_', ' ')
    cat_id = f"{section_id}-{file_name.lower()}"
    cat_label = file_name.replace('_', ' ')
    
    new_cat = f'''            {{
                id: "{cat_id}",
                label: "{cat_label}",
                emoji: "📄",
                description: "Auto-generated section",
                data: {var_name},
                color: "#4a90e2",
            }},'''
            
    # Find section id
    sec_match = re.search(f'id:\\s*"{section_id}"', content)
    if sec_match:
        cat_pos = content.find('categories: [', sec_match.end())
        if cat_pos != -1:
            array_start = cat_pos + len('categories: [')
            content = content[:array_start] + '\n' + new_cat + content[array_start:]
    else:
        new_sec = f'''    {{
        id: "{section_id}",
        label: "{section_label}",
        categories: [
{new_cat}
        ],
    }},'''
        sec_array_start = content.find('export const SECTIONS = [') + len('export const SECTIONS = [')
        content = content[:sec_array_start] + '\n' + new_sec + content[sec_array_start:]
        
    index_path.write_text(content, encoding="utf-8")
    return True


def generate(json_path: Path, dry_run: bool = False) -> tuple[str, bool, bool]:
    """
    Generate (or update) the .js file for a .json source.
    Returns (js_path_str, file_was_changed, index_was_updated).
    """
    js_path     = json_to_js_path(json_path)
    import_path = compute_import_path(js_path, json_path)
    source_rel  = json_path.relative_to(SCRIPT_DIR).as_posix()

    content = TEMPLATE.format(import_path=import_path, source_rel=source_rel)
    
    file_was_changed = False
    
    if not js_path.exists() or js_path.read_text(encoding="utf-8") != content:
        file_was_changed = True
        if not dry_run:
            js_path.parent.mkdir(parents=True, exist_ok=True)
            js_path.write_text(content, encoding="utf-8")
            
    # Always attempt to update index.js (in case JS file existed but index was missing the import)
    index_was_updated = update_index_js(js_path, dry_run=dry_run)

    return str(js_path), file_was_changed, index_was_updated


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--dry-run", action="store_true", help="Preview output without writing files")
    args = parser.parse_args()

    if not JSON_ROOT.exists():
        print(f"[ERROR] json-data folder not found: {JSON_ROOT}", file=sys.stderr)
        sys.exit(1)

    json_files = sorted(JSON_ROOT.rglob("*.json"))
    if not json_files:
        print("[WARN] No .json files found under json-data/")
        return

    created = updated = skipped = index_updated_count = 0

    for json_path in json_files:
        js_path_str, changed, index_updated = generate(json_path, dry_run=args.dry_run)
        rel_js = Path(js_path_str).relative_to(SCRIPT_DIR).as_posix()

        if not changed:
            print(f"  [skip]    {rel_js}")
            skipped += 1
        elif Path(js_path_str).exists() and not args.dry_run:
            print(f"  [updated] {rel_js}")
            updated += 1
        else:
            label = "[dry-run]" if args.dry_run else "[created]"
            print(f"  {label} {rel_js}")
            created += 1
            
        if index_updated:
            index_label = "[dry-run index]" if args.dry_run else "[updated index]"
            print(f"  {index_label} -> Added {Path(js_path_str).stem} to src/data/index.js")
            index_updated_count += 1

    print()
    if args.dry_run:
        print(f"Dry run complete — {created + updated} file(s) would be written, {skipped} unchanged.")
        if index_updated_count > 0:
            print(f"  Furthermore, index.js would be updated with {index_updated_count} new entries.")
    else:
        print(f"Done — {created} created, {updated} updated, {skipped} unchanged.")
        if index_updated_count > 0:
            print(f"       -> index.js was updated with {index_updated_count} new section(s).")


if __name__ == "__main__":
    main()
